mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_2
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_3
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_4
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_5
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_6
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_7
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_8
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_9
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_10
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_11
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_12
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_13
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_14
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_15
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_16
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_17
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_18
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_19
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub
cd ../../1perday_20
mkdir grizyJHK
cd grizyJHK/
sbatch ../../slurmBNSBu.sub

